#include <stdio.h>
#include <stdlib.h>
#include <math.h>
int main(int argc, char *argv[]) {
    int a[10],i,h,j,gcd,ii,jj,t;
    for(t=0;t<7;t++){
        scanf("%d",&a[t]);
    }
    if(a[0]<0){
        a[7]=a[0]*a[2]-a[1];
    }else{
        a[7]=a[0]*a[2]+a[1];
    }
    if(a[4]<0){
        a[8]=a[4]*a[6]-a[5];
    }else{
        a[8]=a[4]*a[6]+a[5];  
    }  
    j=a[6]*a[2];
    switch(a[3]){
        case 0:      
            h=(a[7]*a[6]+a[8]*a[2])/(a[6]*a[2]);
            i=abs((a[7]*a[6]+a[8]*a[2])-a[6]*a[2]*h);                 
            ii=abs((a[7]*a[6]+a[8]*a[2])-a[6]*a[2]*h);
            jj=a[6]*a[2];
            if(i>0){
                while(ii>0&&jj>0){
                    if(ii>jj){
                        ii%=jj;
                    }else{
                        jj%=ii;
                    }
                }
                if(ii>0){
                    i/=ii;
                    j/=ii;
                }else{
                    i/=jj;
                    j/=jj;    
                }
                printf("%d\n",h);
                printf("%d\n",i);
                printf("%d\n",j);
                break;
            }else{
                printf("%d\n",h);
                fputs("0\n",stdout);
                fputs("1\n",stdout);
                break;
            }
        case 1:
            h=(a[7]*a[6]-a[8]*a[2])/(a[6]*a[2]);
            i=abs((a[7]*a[6]-a[8]*a[2])-a[6]*a[2]*h);
            ii=abs((a[7]*a[6]-a[8]*a[2])-a[6]*a[2]*h);
            jj=a[6]*a[2];
            if(i>0){
                while(ii>0&&jj>0){
                    if(ii>jj){
                        ii%=jj;
                    }else{
                        jj%=ii;
                    }
                }
                if(ii>0){
                    i/=ii;
                    j/=ii;
                }else{
                    i/=jj;
                    j/=jj;    
                }
                printf("%d\n",h);
                printf("%d\n",i);
                printf("%d\n",j);
                break;
            }else{
                printf("%d\n",h);
                fputs("0\n",stdout);
                fputs("1\n",stdout);
                break;
            }
        case 2:         
            h=(a[7]*a[8])/(a[6]*a[2]);
            i=abs((a[7]*a[8])-a[6]*a[2]*h);
            ii=abs((a[7]*a[8])-a[6]*a[2]*h);
            jj=a[6]*a[2];
            if(i>0){
                while(ii>0&&jj>0){
                    if(ii>jj){
                        ii%=jj;
                    }else{
                        jj%=ii;
                    }
                }
                if(ii>0){
                    i/=ii;
                    j/=ii;
                }else{
                    i/=jj;
                    j/=jj;    
                }
                printf("%d\n",h);
                printf("%d\n",i);
                printf("%d\n",j);
                break;
            }else{
                printf("%d\n",h);
                fputs("0\n",stdout);
                fputs("1\n",stdout);
                break;
            }
        default:
            h=(a[7]*a[6])/(a[8]*a[2]);
            i=abs((a[7]*a[6])-a[8]*a[2]*h);
            j=a[8]*a[2];
            ii=abs((a[7]*a[6])-a[8]*a[2]*h);
            jj=abs(a[8]*a[2]);
            if(i>0){
                while(ii>0&&jj>0){
                    if(ii>jj){
                        ii%=jj;
                    }else{
                        jj%=ii;
                    }
                }
                if(ii>0){
                    i/=ii;
                    j/=ii;
                }else{
                    i/=jj;
                    j/=jj;    
                }
                printf("%d\n",h);
                printf("%d\n",abs(i));
                printf("%d\n",abs(j));
                break;
            }else{
                printf("%d\n",h);
                fputs("0\n",stdout);
                fputs("1\n",stdout);
                break;
            }
    }
    return 0;
}